//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.239
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperMap.WindowsPhone.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SuperMap.WindowsPhone.Resources.ExceptionStrings", typeof(ExceptionStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 该元素附加项属性ElementsLayer.BBox没有设置 的本地化字符串。
        /// </summary>
        public static string BboxIsNotSet {
            get {
                return ResourceManager.GetString("BboxIsNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能将Feature加到多个FeaturesLayer上 的本地化字符串。
        /// </summary>
        public static string CanntAddToMFLayer {
            get {
                return ResourceManager.GetString("CanntAddToMFLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CRS为空 的本地化字符串。
        /// </summary>
        public static string CRSIsNull {
            get {
                return ResourceManager.GetString("CRSIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目标类型为空 的本地化字符串。
        /// </summary>
        public static string DestinationTypeIsNull {
            get {
                return ResourceManager.GetString("DestinationTypeIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ElementsLayer单独使用时无法添加ShapeBase。 的本地化字符串。
        /// </summary>
        public static string ElementsLayerIsAlone {
            get {
                return ResourceManager.GetString("ElementsLayerIsAlone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高度将小于0 的本地化字符串。
        /// </summary>
        public static string HeightLessThanZero {
            get {
                return ResourceManager.GetString("HeightLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Map的尺度设置与TiledLayer尺度设置不匹配 的本地化字符串。
        /// </summary>
        public static string InvalidMatch {
            get {
                return ResourceManager.GetString("InvalidMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MultiplicationConverter不支持该类型 {0} 的本地化字符串。
        /// </summary>
        public static string InvalidMultiplicationConverter {
            get {
                return ResourceManager.GetString("InvalidMultiplicationConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分辨率数组不能设置为空 的本地化字符串。
        /// </summary>
        public static string InvalidResolutions {
            get {
                return ResourceManager.GetString("InvalidResolutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 比例尺数组不能设置为空 的本地化字符串。
        /// </summary>
        public static string InvalidScales {
            get {
                return ResourceManager.GetString("InvalidScales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法转换为String Array 的本地化字符串。
        /// </summary>
        public static string InvalidStringArray {
            get {
                return ResourceManager.GetString("InvalidStringArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂不支持该Geometry类型 的本地化字符串。
        /// </summary>
        public static string InvalidSupportGeometry {
            get {
                return ResourceManager.GetString("InvalidSupportGeometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法成功转换为CoordinateReferenceSystem 的本地化字符串。
        /// </summary>
        public static string InvalidToCRS {
            get {
                return ResourceManager.GetString("InvalidToCRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法成功转换为DoubleArray 的本地化字符串。
        /// </summary>
        public static string InvalidToDoubleArray {
            get {
                return ResourceManager.GetString("InvalidToDoubleArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的URI模式宿主 的本地化字符串。
        /// </summary>
        public static string InvalidURISchemeHost {
            get {
                return ResourceManager.GetString("InvalidURISchemeHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 强烈程度的范围大于1或者小于0 的本地化字符串。
        /// </summary>
        public static string IvalidIntensity {
            get {
                return ResourceManager.GetString("IvalidIntensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该Layer已经隶属于其他Map 的本地化字符串。
        /// </summary>
        public static string LayerToMap {
            get {
                return ResourceManager.GetString("LayerToMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请求繁忙 的本地化字符串。
        /// </summary>
        public static string OperationIsBusy {
            get {
                return ResourceManager.GetString("OperationIsBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数错误 的本地化字符串。
        /// </summary>
        public static string ParametersError {
            get {
                return ResourceManager.GetString("ParametersError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本解析失败 的本地化字符串。
        /// </summary>
        public static string ParseFailed {
            get {
                return ResourceManager.GetString("ParseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Point2Ds为空 的本地化字符串。
        /// </summary>
        public static string Point2DsIsNull {
            get {
                return ResourceManager.GetString("Point2DsIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请确认Web服务器根目录下存在跨域策略文件，服务地址等参数是否正确。 的本地化字符串。
        /// </summary>
        public static string PolicyFileAvailable {
            get {
                return ResourceManager.GetString("PolicyFileAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 半径范围小于1 的本地化字符串。
        /// </summary>
        public static string RadiusLessThanOne {
            get {
                return ResourceManager.GetString("RadiusLessThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 right必须大于left 的本地化字符串。
        /// </summary>
        public static string RightLessThanLeft {
            get {
                return ResourceManager.GetString("RightLessThanLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RootElement为空 的本地化字符串。
        /// </summary>
        public static string RootElementIsNull {
            get {
                return ResourceManager.GetString("RootElementIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须以HTTP(S)模式启动应用程序，请确认把您的网站设为启动项目。 的本地化字符串。
        /// </summary>
        public static string SchemeError {
            get {
                return ResourceManager.GetString("SchemeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务地址错误 的本地化字符串。
        /// </summary>
        public static string ServiceAddressError {
            get {
                return ResourceManager.GetString("ServiceAddressError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请确认您的地图服务已经启动，地图名称等参数是否正确。 的本地化字符串。
        /// </summary>
        public static string ServiceStarted {
            get {
                return ResourceManager.GetString("ServiceStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 坐标解析失败 的本地化字符串。
        /// </summary>
        public static string TextParseFailed {
            get {
                return ResourceManager.GetString("TextParseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 top必须大于bottom. 的本地化字符串。
        /// </summary>
        public static string TopLessThanBottom {
            get {
                return ResourceManager.GetString("TopLessThanBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 宽度小于0 的本地化字符串。
        /// </summary>
        public static string WidthLessThanZero {
            get {
                return ResourceManager.GetString("WidthLessThanZero", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 数量小于1 的本地化字符串。
        /// </summary>
        public static string CountLessThanOne
        {
            get
            {
                return ResourceManager.GetString("CountLessThanOne", resourceCulture);
            }
        }
    }
}
